### ISSUE TITLE
Feature Request: File Upload/Download Functionality

### ISSUE THREAD

**Issue by HaxorGaruda** [Ne0nd0g/merlin#1]
nice evasion for antivirus, but need download or upload file on agent (victim) .. thanks ...

**Comment by Ne0nd0g** [comment]
@HaxorGaruda I agree with you. I'll add it to list of TODO items and work on getting it implemented. Any chance you're interested in helping by submitting a pull request to add the functionality?

**Comment by ahhh** [comment]
@Ne0nd0g if you point me toward the feature list I can start working on some PRs

**Comment by twigatech** [comment]
@Ne0nd0g @ahhh Same here point out a list and I will jump on it.

**Comment by Ne0nd0g** [comment]
@ahhh and @twigatech thank you for helping out. I appreciate your help. I don't currently have a feature list, but I'll work one in the next couple of days and get it published.

**Comment by twigatech** [comment]
#6 Upload portion of the feature.

**Comment by Ne0nd0g** [comment]
This was completed in #6 and subsequent commits. Thanks @twigatech.
