### ISSUE TITLE
Error TLS Handshake

### ISSUE THREAD

**Issue by horiz0ec3** [Ne0nd0g/merlin#10]
When the merlinserver already running and victim open the link i have a problem on my merlin server (TLS Handshake Error : EOF). anyone can help me resolve this error ?

TLS handshake error from 192.168.*.**:****: remote error: unknown certificate authority
TLS handshake error from 192.168.*.**:****: remote error: EOF

**Comment by Ne0nd0g** [comment]
Hello @horiz0ec3, what version of the server and agent are you running? When you're talking about the victim opening a link, are you talking about using the JavaScript agent?

**Comment by horiz0ec3** [comment]
i just downloaded merlin 4 days ago, the newest version . . . and i want get some agent with merlin server, is possible get the agent with just my merlin server ip like 192.168.21.134:443 and opened in victim device ??

**Comment by Ne0nd0g** [comment]
I wasn't sure if you were running one of the release versions or if you were compiling Merlin on your own. Yes, it is possible to have agents talked with your server at 192.168.21.134:443. How did you tell the agent where the server is? What operating system are you running the server on and what operating system are you running the agent on? Can you show me the output of the agent being run with the `-v` flag?

**Comment by horiz0ec3** [comment]
this is SC for My problems 
![merlin error](https://user-images.githubusercontent.com/25809154/35311700-67578e60-00ea-11e8-8ce9-93d2795de79c.png)

![merlin agent](https://user-images.githubusercontent.com/25809154/35311719-78c9334c-00ea-11e8-9439-c474dba51ff2.PNG)

![merlin agent withou https](https://user-images.githubusercontent.com/25809154/35311731-872f759a-00ea-11e8-8b3b-32e838b02f31.png)

Certificate Untrusted if i open the link (https://192.168.21.134:443) with https and merlin server still have tls error
Same problem if i open the link (192.168.21.134:443)

**Comment by Ne0nd0g** [comment]
@horiz0ec3, you will need to run the merlinAgent executable to connect an agent to the server. You can't access the Merlin server with your web browser. 

You will need to purchase or create valid SSL/TLS certificates with something like LetsEncrypt to prevent from getting the certificate untrusted message.

**Comment by horiz0ec3** [comment]
is agent will connect with server if agent run executable ? no other way for getting agent ?

**Comment by Ne0nd0g** [comment]
The agent will connect with the server so long as server is listening on 127.0.0.1 OR you specify the server's address with the `-url` flag when you execute the agent.

There is another method that is currently in development. This method requires you to inject the Merlin JavaScript library into an existing web page. There is a test page that you can serve and visit, but it isn't the same as trying to visit MerlinServer with your web browser.

**Comment by Ne0nd0g** [comment]
@horiz0ec3 were you able to get everything sorted out? If so, I'm going to close this issue. If not, let me know how I can help.
