### ISSUE TITLE
Setting Responce Header "Content-Type" not Taking Effect

### ISSUE THREAD

**Issue by Fi1o** [Ne0nd0g/merlin#100]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: Custom version
* Merlin Build: 
* Go Version: 1.14
* GOPATH Environment Variable:
* GOROOT Environment Variable:
* Operating System:

### Expected Behavior

Set header content type to application/octet for serving files using http.ServeFile

When you go to https://x.x.x.x/filename it should return 200, download the file and you should see response headers specifying content type application/octet-stream

note: file used was a 9mb+ *.bin file

### Actual Behavior

Responce code 304, file still served but data is encoded wrong (i might be using encoded wrong? bunch of weird symbols and accents on letters). No content-type is set

### Steps to Reproduce Behavior

s.mux.handlefunc to serve a file with http.ServeFile and then set content type

### Misc Information

solved by commenting out MaxHeaderBytes: 1 << 20 in http2.go

**Comment by Ne0nd0g** [comment]
Merlin isn't intentionally configured to serve files at all. The expected behavior when you visit https://x.x.x.x/filename is that you get a 404. Can you elaborate on this issue? Can you show an example?
