### ISSUE TITLE
[Question] Why go.mod contains the full name "github.com/Ne0nd0g/merlin" instead of just "merlin"

### ISSUE THREAD

**Issue by g3rzi** [Ne0nd0g/merlin#103]
Hello, 
this is not a bug, just a question.    
Is there a reason to use the full name of the repository in GitHub as the name of the module?
https://github.com/Ne0nd0g/merlin/blob/be117de982e568bca441e2b57ff4ed5739148f41/go.mod#L1  

Why you didn't use just `module merlin` ?

**Comment by Ne0nd0g** [comment]
There was not a specific reason. From my understanding that is the desired output when you run `go mod init` as shown here:

If you just want to chat, please join the #merlin channel in the [BloodHoundGang](https://bloodhoundgang.herokuapp.com/) Slack
