### ISSUE TITLE
Merlin server returns "Invalid job Type 0" when running modules

### ISSUE THREAD

**Issue by 16032144** [Ne0nd0g/merlin#107]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 1.0.0
* Merlin Build: "7ea5237b6d25a86e9308395666857305f1b42da7" (Pre-compiled)
* Go Version: go1.15.9 
* GOPATH Environment Variable: N/A
* GOROOT Environment Variable: N/A
* Operating System: Kali Linux (Linux/amd64) (Server), Windows 10 (Win/amd64)

### Expected Behavior
When selecting a module and setting an Agent, the module should send a job to the Merlin-agent.

### Actual Behavior
Currently when trying to run a module, the server responds with "Invalid job type 0"

### Steps to Reproduce Behavior
Info about the agent that is connected to the merlin server:
![info](https://user-images.githubusercontent.com/59948445/119852404-8f07cd80-bf0f-11eb-99de-0a98ec9a3643.png)

Selecting the minikatz module and try to run it. It returns the "invalid job type 0" message.
![Minikatz](https://user-images.githubusercontent.com/59948445/119852417-90d19100-bf0f-11eb-8c7f-0c7ce04fee9b.png)

Minidump does show a similar problem, but a don't know if this is caused by the same bug. Although it prints out: "Lsass dump succesful", the dump isn't found in the "/data/agents/"Agent ID"/"
![Minidump](https://user-images.githubusercontent.com/59948445/119852415-90d19100-bf0f-11eb-9a35-30bd1dc82a63.png)

**Comment by Ne0nd0g** [comment]
Looks like the problem is due to this hard coded `cmd` value. I removed functionality for that and replaced it with `run`. I'll get a patch pushed out soon and likely implement constants so that way this particular issues is less likely to come up. 

https://github.com/Ne0nd0g/merlin/blob/master/pkg/api/modules/modules.go#L108
