### ISSUE TITLE
multiple-value "github.com/satori/go.uuid".NewV4() in single-value context

### ISSUE THREAD

**Issue by Kamizuma** [Ne0nd0g/merlin#11]
merlinagent/main.go  var hostUUID = uuid.NewV4(), cant compile.

Using Goland as IDE

merlinserver/main.go

cmd/merlinserver/main.go:176:10: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:180:11: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:186:11: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:312:8: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:312:26: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in field value
cmd/merlinserver/main.go:317:8: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:318:8: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:319:8: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:320:8: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:321:8: cannot use j.ID (type "github.com/Ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index

**Comment by Ne0nd0g** [comment]
@Kamizuma , I'm also using the GoLand IDE. I really like it. Can you share with me what your GOPATH and GOROOT are set to? Are you using the master or dev branch?

**Comment by Kamizuma** [comment]
I am using the master branch, seems like satori broke the api of uuid with update ? are we expecting when patch ?

**Comment by Ne0nd0g** [comment]
The value of using Vendoring is that Merlin is tied to version I distribute and not the author's version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ne0nd0g** [comment]
@Kamizuma , were you able to overcome this issue?
