### ISSUE TITLE
Feature Request: Dynamic DNS support

### ISSUE THREAD

**Issue by nomercyfin** [Ne0nd0g/merlin#12]
Would be awesome if we could use dynamic dns to not worry with all ip-changes...

**Comment by Ne0nd0g** [comment]
@Kamizuma could you please provide an example of what you mean? The client will take dynamic DNS names when using the `-url` flag.

**Comment by ejohnu** [comment]
I am not entirely sure what the intent of this feature request is. I have implemented a feature to bypass the system resolver and use a custom DNS resolver (udp, DOT or DOH) for resolution. I can submit a PR, if that is useful to others.

**Comment by ejohn** [comment]
I am not entirely sure what the intent of this feature request is. I have implemented a feature to bypass the system resolver and use a custom DNS resolver (udp, DOT or DOH) for resolution. I can submit a PR, if that is useful to others.

**Comment by Ne0nd0g** [comment]
It has been over a year and @nomercyfin has not responded to my request for additional information.
@ejohn I'm all for a configurable option to bypass the system resolver and use a custom resolver using any of the protocols you mentioned.
