### ISSUE TITLE
Usage of Let's Encrypt

### ISSUE THREAD

**Issue by symmetrisch** [Ne0nd0g/merlin#120]
I converted default *Let's Encrypt* files

`openssl x509 -outform der -in fullchain.pem -out server.crt`
`cp privkey.pem server.key`

but Merlin teamserver ignores them 

`[-] Certificate was not found at:` (path was correct)

Am I doing something wrong?

**Comment by Ne0nd0g** [comment]
What version of Merlin were you using? What operating system were you using? The output format should be PEM, not DER.

**Comment by symmetrisch** [comment]
Thanks for your fast reply. Latest version on latest Kali/Debian.
Yes, your note solved it! So, for the record, there is "nothing" to do...
`cp fullchain.pem server.crt`
`cp privkey.pem server.key`
