### ISSUE TITLE
Websocket over tcp

### ISSUE THREAD

**Issue by yellow-starburst** [Ne0nd0g/merlin#125]
I noticed the websocket functionality is via UDP communication. Why is that?
TCP is stealthier and more reliable.

**Comment by Ne0nd0g** [comment]
Merlin does not use websockets. However, it does use HTTP/3 which works on top of [QUIC](https://datatracker.ietf.org/doc/rfc9000/), a UDP protocol. The HTTP1&2 protocols use TCP. If you just want to chat about Merlin, please sign up for the [BloodHoundGang](https://bloodhoundgang.herokuapp.com/) slack and stop by the #merlin channel.
