### ISSUE TITLE
Merlin not building with go 1.18

### ISSUE THREAD

**Issue by smijolovic** [Ne0nd0g/merlin#126]
go build -ldflags '-X main.build=da8a988e39f656cd0d81c992e03d5cfd7feed562 -buildid=' -o merlinserver main.go
github.com/lucas-clemente/quic-go/internal/qtls
../pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

Looks like there is a dependency mapped to merlin that doesn't support 1.18

**Comment by Ne0nd0g** [comment]
Thanks for submitting this @smijolovic . I'll work on getting it updated to support go v1.18. As a work around, please use go v1.17.

**Comment by Ne0nd0g** [comment]
Fixed with 0a3cbf83753b4b213ecc2fcd1c58560f56a2f8ff

**Comment by smijolovic** [comment]
Compiles clean on 1.18.1.  Thanks!  Great response.
