### ISSUE TITLE
Uninstall Mythic?

### ISSUE THREAD

**Issue by MavericksGooses** [Ne0nd0g/merlin#128]
Hello,

I followed your instructions on installing mythic and merlin, however after doing so my Apache Guacamole server stopped working. Is there anyway I can uninstall Mythic?

**Comment by Ne0nd0g** [comment]
Hey @MavericksGooses, this reported issue doesn't relate to this project. Sounds like you have a question about Mythic which can be found at https://github.com/its-a-feature/Mythic. This issue doesn't seem like a bug or a problem, but more of a question. If you just want to chat about Mythic, I recommend joining the [BloodHoundGang](https://bloodhoundgang.herokuapp.com/) Slack and asking the community in the #mythic channel. 

You can uninstall the Merlin payload using the Mythic CLI with a command like: `sudo ./mythic-cli uninstall merlin`

You can uninstall Mythic using the Mythic CLI to stop Mythic with a command like: `sudo ./mythic-cli mythic stop` and then delete all the files and purge the Docker images and containers.
