### ISSUE TITLE
socks5 listener

### ISSUE THREAD

**Issue by trapisone** [Ne0nd0g/merlin#134]
Hii! :D
How should the socks5 listener be used in merlinServer?.

merlinServer (ip_kali):
`socks start 0.0.0.0:9053`

merlin-Agent:
`./merlin-agent -url "https://ip_kali" -proto "https"`

then I should use something like this?: (on the machine where I run merlinServer)
`ssh -f -N -D 0.0.0.0.0:1080 -p 9053 user@localhost`

`proxychains command ...`

if so, in the merlin-Agent I get the following:
"socks: Unsupported SOCKS version: [83]"

I'm sorry if I'm doing a barbarity XDD, I'm a newbie.

Best regards. :D

### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 1.5.0
* Merlin Build: nonRelease
* Go Version: go1.18.3
* GOPATH Environment Variable: null
* GOROOT Environment Variable: null
* Operating System: Linux

**Comment by Ne0nd0g** [comment]
You can exclude the ssh command and just use proxy chains to connect

**Comment by trapisone** [comment]
Hi, thanks for replying :D,


I excluded the ssh, but in the agent it tells me:
`"[ERR] socks: Failed to authenticate: io: read/write on closed pipe".`

using on the merlinServer machine:
```
❯ proxychains curl http://httpbin.org/get
[proxychains] configuration file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict string ...  127.0.0.1:9053 ... httpbin.org:80 <--Socket error or timeout!
```
in proxychains configuration:
/etc/proxychains.conf

`socks5 127.0.0.1 9053 <credentials here?>`

**Comment by Ne0nd0g** [comment]
This is a different error. The connection timed out before SOCKS connection could finish and curl closed the connection. Try setting the sleep and skew to `0` in the agent before using SOCKS.

**Comment by trapisone** [comment]
It worked, thank u very much :'D
Best regards.
