### ISSUE TITLE
MerlinServer just showing JSON data but no actual GUI

### ISSUE THREAD

**Issue by JitBox** [Ne0nd0g/merlin#146]
I have followed the instructions very step by step but when I try to run the MerlinServer, I get some JSON back of info showing its working, but I have no GUI interface like the Wizard hat and Merlin CLI. Has this been observed before? Not sure what I could be doing wrong. I have tried with several versions of Go.

![image](https://github.com/Ne0nd0g/merlin/assets/64562427/3be94ae0-fa71-459d-8d98-f1d716d33c44)

**Comment by Ne0nd0g** [comment]
@JitBox the latest version of Merlin separates the server from the user interface. You will need to execute the Merlin command-line interface program to connect to the server. The CLI is pre-packaged with the server in the `data/bin/` directory. Alternatively, you can build or download the CLI from here https://github.com/Ne0nd0g/merlin-cli.

Can you share with me which instructions you used so I can update them?
