### ISSUE TITLE
Python to Go because of you

### ISSUE THREAD

**Issue by s1st3r** [Ne0nd0g/merlin#19]
Been doing Go at Udemy because of this tool and its amazing that i always thought Go could be hard only to find it really sexy.
Am thinking of trying to make merlin a little modular, like screenshots, webcam, microphone etc.

Thankx Ne0

**Comment by Ne0nd0g** [comment]
@s1st3r , glad you've found it useful. Merlin has some limited modular functionality using JSON files to describe the module. Is that the avenue you are looking at regarding your comments on screenshots, webcam, microphone etc?

Check out BetterCap, it is also a really well written program in Go https://github.com/bettercap/bettercap

**Comment by s1st3r** [comment]
Thankx, am still in class at Edemy, hope to finish by end month and then contribute as much as i can on modular level

**Comment by Ne0nd0g** [comment]
Cool, let me know what you come up with. The module support still needs a fair amount of work. Catch up with me on the Slack group if you want to talk more about it.
