### ISSUE TITLE
cannot use hostUUID

### ISSUE THREAD

**Issue by RealLinkers** [Ne0nd0g/merlin#2]
Hello,

Thank you for your efforts in creating this nice project.
I have run into the following issue:
When running or compiling agent
# command-line-arguments
cmd/merlinagent/main.go:154: cannot use hostUUID (type "github.com/satori/go.uuid".UUID) as type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID in field value
cmd/merlinagent/main.go:200: cannot use hostUUID (type "github.com/satori/go.uuid".UUID) as type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID in field value
cmd/merlinagent/main.go:461: cannot use hostUUID (type "github.com/satori/go.uuid".UUID) as type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID in field value
Makefile:51: recipe for target 'agent-linux' failed
make: *** [agent-linux] Error 2

Server
# command-line-arguments
cmd/merlinserver/main.go:176:10: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:180:11: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:186:11: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:312:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:312:26: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in field value
cmd/merlinserver/main.go:317:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:318:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:319:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:320:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:321:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:321:8: too many errors
Makefile:47: recipe for target 'server-linux' failed
make: *** [server-linux] Error 2

Running it via script
go run cmd/merlinserver/main.go
# command-line-arguments
cmd/merlinserver/main.go:176:10: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:180:11: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:186:11: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:312:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:312:26: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in field value
cmd/merlinserver/main.go:317:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:318:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:319:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:320:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:321:8: cannot use j.ID (type "github.com/ne0nd0g/merlin/vendor/github.com/satori/go.uuid".UUID) as type "github.com/satori/go.uuid".UUID in map index
cmd/merlinserver/main.go:321:8: too many errors

**Comment by Ne0nd0g** [comment]
@RealLinkers , thanks for reporting this. Let me see if I can duplicate the problem.

- Can you share with me what version of Go you're using?
- Can you share with me what your GOPATH environment variable is?
- Can you share with me what OS and version you're using?

Do the pre-compiled binary files work?

Another user reported a similar problem to this on the Reddit post. As a work around, you can try to delete the vendor folder and manually `go get` the package. https://www.reddit.com/r/netsec/comments/7ksrhy/introducing_merlin_a_crossplatform/

**Comment by Ne0nd0g** [comment]
@RealLinkers I've updated master branch to fix some of the vendoring problems. Make sure that your $GOPATH environment variable is set so that merlin looks like this:
`$GOPATH/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/main.go`

**Comment by RealLinkers** [comment]
go version go1.7.5 linux/amd64
Enviroment variable:
export GOPATH=$HOME

Binary's work just fine.
I was testing on Ubuntu 16.04

**Comment by Ne0nd0g** [comment]
Was Merlin in `$HOME/src/github.com/Ne0nd0g/merlin`?

I ran through these commands on an Ubuntu VM and did not have any errors:
```
wget https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
mkdir $HOME/work
export GOPATH=$HOME/work
go get github.com/Ne0nd0g/merlin
cd $HOME/work/src/github.com/Ne0nd0g/merlin
```

**Comment by Ne0nd0g** [comment]
@RealLinkers Were you able to resolve this issue?

**Comment by Ne0nd0g** [comment]
@RealLinkers, I wanted to follow up one more time before I mark this issue as closed.

**Comment by Ne0nd0g** [comment]
Closing issue because submitter has been unresponsive for 30+ days.
