### ISSUE TITLE
var cmd *exec.Cmd repeated instance for agent.go on agent_windows.go

### ISSUE THREAD

**Issue by s1st3r** [Ne0nd0g/merlin#20]
Still going through code, but wondering should we rename some instances here or actual files, seems there is bug? i had to rename my code inside pkg/agent the func ExecuteCommand to EC in  exec_windows

**Comment by Ne0nd0g** [comment]
Please re-submit this issue using the issue template.

**Comment by Ne0nd0g** [comment]
@s1st3r I wanted to follow up with you on this. Please re-submit this issue using the issue template or close the issue.

**Comment by Ne0nd0g** [comment]
Closing this issue due to lack of information, absence of issue template, and 60 days without communication from user.
