### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by Explorer1092** [Ne0nd0g/merlin#21]
prompt is missing "n"

 linux/x64/bash/credentials/MimiPengui
<img width="507" alt="2018-06-20 9 04 59" src="https://user-images.githubusercontent.com/32663226/41660185-ec0fdcbe-74cd-11e8-9a9f-e5a38812bdfc.png">

**Comment by Ne0nd0g** [comment]
@Explorer1092 thank you for reporting this. I've found the problem and I will push a fix to the dev branch soon. Error is in the `GetModuleList` function of the `modules` package on line 159. I need to change the function from `m = strings.TrimRight(m, ".json")` to `m = strings.TrimSuffix(m, ".json")` to use the `TrimSuffix` function.
