### ISSUE TITLE
custom server URL

### ISSUE THREAD

**Issue by serkeft1n** [Ne0nd0g/merlin#25]
at https://github.com/Ne0nd0g/merlin/wiki/Building-or-Running-from-Source
the instructions have a small error, it says use the flag main.URL but it needs to be main.url in lowercase

**Comment by Ne0nd0g** [comment]
Good catch. I have updated the Wiki to match. Thanks for reporting this.

**Comment by serkeft1n** [comment]
Turns out it's main.url for the .exe but main.URL for the dll. Also in the agent-dll rule in my Makefile I added -s so the dll isn't so big
