### ISSUE TITLE
Error in DLL compilation

### ISSUE THREAD

**Issue by msidagni** [Ne0nd0g/merlin#27]
Merlin version: 0.6.0 Master
Go Version: go version go1.10.4 linux/amd64

When I try to compile the DLL with make agent-dll I get this error:

make agent-dll
export GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ CGO_ENABLED=1; \
go build -buildmode=c-archive -o data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360/main.a cmd/merlinagentdll/main.go; \
cp data/bin/dll/merlin.c data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360; \
x86_64-w64-mingw32-gcc -shared -pthread -o data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360/merlin.dll data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360/merlin.c data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360/main.a -lwinmm -lntdll -lws2_32
# command-line-arguments
cmd/merlinagentdll/main.go:37: too many arguments in call to agent.New
	have (string, bool, bool)
	want (bool, bool)
cmd/merlinagentdll/main.go:38: not enough arguments in call to a.Run
	have (string)
	want (string, string)
x86_64-w64-mingw32-gcc: error: data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360/main.a: No such file or directory
make: *** [Makefile:56: agent-dll] Error 1

**Comment by Ne0nd0g** [comment]
Would you be able to provide me with the MD5 hash of `cmd/merlinagentdll/main.go` and `pkg/agent/agent.go`?

I wasn't able to duplicate the issue. I installed Go on a fresh system, cloned the repo, and compiled the DLL without any errors.
