### ISSUE TITLE
Feature Request: domain fronting support

### ISSUE THREAD

**Issue by Viss** [Ne0nd0g/merlin#32]
## Feature Request!

To support domain fronting the only thing needed is the ability to add a host header to the http requests.

being able to do something like: 
`./merlinagent -u https://images.amazon.com -p 443 -front 1234123412341234.cloudfront.net`

could add the header:
`Host: 1234123412341234.cloudfront.net`
to the request, and the connection would be fronted through images.amazon.com.

**Comment by Ne0nd0g** [comment]
Thanks @Viss . I agree and I'll get that setup for my next push. I'll have time to accomplish this in the next couple of days.

**Comment by Viss** [comment]
ah excellent!
I figured it would be a quick one, because its literally just adding single header line :D

Also, if that happens soon, I can use it on this engagement I'm on! \o/

**Comment by Ne0nd0g** [comment]
CloudFront can't be used for domain fronting with HTTP/2 because they always forward requests over HTTP/1.1. Copied this directly from AWS console:

> For viewer requests, choose the versions of the HTTP protocol that you want CloudFront to accept. In general, HTTP/2 is faster. CloudFront always forwards requests to the origin using HTTP/1.1.

**Comment by pbssubhash** [comment]
Hey @Ne0nd0g, Any plans for adding this feature?

**Comment by Ne0nd0g** [comment]
Added in ace580b66f4e724b90723f4ac3f08ccd8f13235e for HTTP/1.1 connections only.
