### ISSUE TITLE
Agent Crashes on Module Execution

### ISSUE THREAD

**Issue by benichmt1** [Ne0nd0g/merlin#33]
### Prerequisite
* [ x ] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [ x ] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [ x ] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: Server 0.6.0
* Merlin Build: Latest Source
* Go Version: go1.11.2 windows/amd64
* GOPATH Environment Variable: C:\Users\me\go
* GOROOT Environment Variable: C:\go
* Operating System: Windows 7 x64

### Expected Behavior
The module runs successfully
### Actual Behavior
The application panics and crashes
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x7408d1]

goroutine 6 [running]:
github.com/Ne0nd0g/merlin/pkg/agents.AddJob(0xffffffffffffffff, 0xffffffffffffffff, 0x84f84d, 0x3, 0xc4201d6460, 0x7, 0xa, 0x0, 0x0, 0x0, ...)
        /mnt/c/Data/Dev/Go/src/github.com/Ne0nd0g/merlin/pkg/agents/agents.go:366 +0x511
github.com/Ne0nd0g/merlin/pkg/cli.Shell()
        /mnt/c/Data/Dev/Go/src/github.com/Ne0nd0g/merlin/pkg/cli/cli.go:169 +0x2403
created by main.main
        /mnt/c/Data/Dev/Go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/main.go:66 +0x472
```
### Steps to Reproduce Behavior
1. Download and extract the 0.6.0 server release (Ubuntu DO droplet). Run the server.
2. On the compiling box (Windows), download the source (go get github.com/Ne0nd0g/merlin)
3. Move into the relevant directory and compile (I used go build)
   `go build -ldflags "-H=windowsgui -x main.url=https://myhost:443/" -o agent.exe cmd/merlinagent/main.go`
4. The application compiles successfully. Double clicking successfully stages a session.
5. `use module windows/64/powershell/powersploit/Invoke-Mimikatz`; `set agent all`; `run` crashes the server.

### Misc Information
Also compiled with TDM-GCC as recommended. This did not fix the issue.

**Comment by Ne0nd0g** [comment]
@benichmt1 thanks for reporting this. I have verified this bug exists. However, I ran a different version of the server from the DEV branch and did not get the error. Looks like I might have unknowingly fixed that bug. This might be related to issue #23 . Can you try to compile the server from the DEV branch and see if you get the same error?

**Comment by Ne0nd0g** [comment]
@benichmt1 wanted to follow up with you on this issue to see if you've tried the DEV branch.

**Comment by benichmt1** [comment]
Hi there,

The dev branch fixed the issue. 

Just curious, to take advantage of the QUIC protocol for the Windows agent, what are the compiler flags to use? I noticed self-compiling defaults to HTTP/2. I was trying to use a self-contained binary that defaults to QUIC without command line args.

**Comment by benichmt1** [comment]
edit: I spoke too soon:
```error walking the path "/root/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/data/modules": lstat /root/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/data/modules: no such file or directory
prevent panic by handling failure accessing a path "/root/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/data/modules": lstat /root/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/data/modules: no such file or directory
error walking the path "/root/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/data/modules": lstat /root/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/data/modules: no such file or directory
```

this is using the quic protocol, dev branch for server and client.

**Comment by Ne0nd0g** [comment]
To default to quick, change this line in cmd\merlinagent\main.go

`protocol := flag.String("proto", "h2", "Protocol for the agent to connect with [h2, hq]")`

to

`protocol := flag.String("proto", "hq", "Protocol for the agent to connect with [h2, hq]")`

You can also change this line in cmd\merlinagent\main.go

`a := agent.New(*protocol, *verbose, *debug)`

to

`a := agent.New("hq", *verbose, *debug)`

What file path were you running the server out of? It is hard coded so that the server is run in the same directory as the `data` directory. It looks like you might have been running the server out of the `cmd/merlinserver` directory instead.

**Comment by Ne0nd0g** [comment]
@benichmt1 I wanted to follow up with you on this before I close the issue.

**Comment by benichmt1** [comment]
I am still having issues. I think some of my core issues were the minimum GO version required for QUIC. It looks like the QUIC-GO library only supports Go 1.9+. 

I plan on getting a new dev environment and trying it from there. I have no issues doing a regular go build on my Windows machine from one of the older releases.

**Comment by benichmt1** [comment]
Fixed in latest master, tested with h2 and hq protocols. In
Go version:
`go version go1.11.4 linux/amd64`


Installed via snap on DigitalOcean (`sudo snap install --classic go`)

Go env (server):

```GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/3095"
GOTMPDIR=""
GOTOOLDIR="/snap/go/3095/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build036921903=/tmp/go-build -gno-record-gcc-switches"
```

Same Go version on Windows client. Compiled with `go build` and `ldflags` params.
