### ISSUE TITLE
Merlin not showing host/platform/user information

### ISSUE THREAD

**Issue by unkn0wn2u** [Ne0nd0g/merlin#34]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: Version: 0.1.4 Beta
* Merlin Build: https://github.com/Ne0nd0g/merlin/releases/download/v0.1.4/merlinServer-Linux-x64-v0.1.4.7z
* Go Version: go version go1.10.4 linux/amd64
* GOPATH Environment Variable: 
* GOROOT Environment Variable:
* Operating System: Linux parrot 4.17.0-parrot17-amd64 #1 SMP Parrot 4.17.17-1parrot17 (2018-08-27) x86_64 GNU/Linux

### Expected Behavior

Merlin on connection showing victim information about host/user/platfrom

### Actual Behavior

![image](https://user-images.githubusercontent.com/43794090/49601436-bfdd9c00-f97d-11e8-8217-26e9e63c02a4.png)

It is not showing it.

### Steps to Reproduce Behavior

Create executable for windows and execute it on the victim with merlin-agent -url IP:PORT

### Misc Information

Is there anything I can do to fix it ?

**Comment by Ne0nd0g** [comment]
@unkn0wn2u can you please try the latest release to see if you get the same error?
