### ISSUE TITLE
Dll Compilation Error

### ISSUE THREAD

**Issue by pasoles** [Ne0nd0g/merlin#35]
I think that its not an issue of Merlin but an issue of gcc.
When I try to compile (gcc -shared -pthread -o merlin.dll merlin.c main.a -lwinmm -lntdll -lws2_32) both in windows and kali I get an error exit status and many undefined references.
![image](https://user-images.githubusercontent.com/10215004/49690083-c746a600-fb33-11e8-9a62-0b2c36d338f1.png)
Which version of gcc do you use? Have you done any special modifications?
Thanks

**Comment by Ne0nd0g** [comment]
Try adding these command line options 

`gcc -shared -pthread -o merlin.dll merlin.c main.a -lwinmm -lntdll -lws2_32`

You can also try `make agent-dll`

More details are here  https://github.com/Ne0nd0g/merlin/wiki/DLL-Agent

**Comment by pasoles** [comment]
I repeated all the process again in windows and worked like a charm.
In linux I still get the aforementioned error message. Maybe its something about charcacters encoding, spaces etc.
Anyway thanks for your fast response

**Comment by pasoles** [comment]
Yes I was getting the same errors.
I figured out what was going wrong. The compiler couldn't find the libraries(libntdll etc) so I had to specify the path:

`x86_64-w64-mingw32-gcc -shared -pthread -o merlin.dll merlin.c main.a -lwinmm -lntdll -lws2_32 -L /usr/x86_64-w64-mingw32/lib/`
