### ISSUE TITLE
Error in DLL compilation (Files missing?)

### ISSUE THREAD

**Issue by pentestitde** [Ne0nd0g/merlin#36]
### Prerequisite
* [ ] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [ ] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [ ] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: latest
* Merlin Build:
* Go Version: latest
* GOPATH Environment Variable: /home/frank/merlin
* GOROOT Environment Variable: /usr/local/go
* Operating System: Ubuntu 18.04

### Expected Behavior
compiling DLL from source 

### Actual Behavior

frank@ubuntu:~/merlin/data/bin/dll$ go build -buildmode=c-archive ../../../cmd/merlinagentdll/main.go
../../../cmd/merlinagentdll/main.go:28:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/agent" in any of:
	/usr/local/go/src/github.com/Ne0nd0g/merlin/pkg/agent (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/pkg/agent (from $GOPATH)

# Steps to Reproduce Behavior

### Misc Information
There is no src/github.com/Ne0nd0g directory in the repository?

**Comment by Ne0nd0g** [comment]
Can you please tell me the numerical version of Merlin you're using along with the build?

Can you please confirm that your `GOPATH` directory contains this path: 

`/home/frank/merlin/src/github.com/Ne0nd0g/merlin` ? If not, you will need to setup your environment. To do so, move into the following directory (create it if it doesn't exist) and do a git clone of the repository:

`/home/frank/merlin/src/github.com/Ne0nd0g$ git clone https://github.com/Ne0nd0g/merlin`

You can download per-compiled versions of Merlin from the releases page.

**Comment by pentestitde** [comment]
Hi Russel,


I dit everything like you explained, but receive the following error:

frank@ubuntu:~/merlin/src/github.com/Ne0nd0g/merlin$ echo $GOPATH
/home/frank/merlin/src/github.com/Ne0nd0g/merlin/
frank@ubuntu:~/merlin/src/github.com/Ne0nd0g/merlin$ make
export GOOS=windows;export GOARCH=amd64;go build -ldflags "-s -X main.build=f04436131f2d88204765f905395f7d404103e360" -o data/temp/v0.6.0/f04436131f2d88204765f905395f7d404103e360/merlinServer-Windows-x64.exe cmd/merlinserver/main.go
cmd/merlinserver/main.go:34:2: cannot find package "github.com/Ne0nd0g/merlin/pkg" in any of:
	/usr/lib/go-1.10/src/github.com/Ne0nd0g/merlin/pkg (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/Ne0nd0g/merlin/pkg (from $GOPATH)
cmd/merlinserver/main.go:29:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/banner" in any of:
	/usr/lib/go-1.10/src/github.com/Ne0nd0g/merlin/pkg/banner (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/Ne0nd0g/merlin/pkg/banner (from $GOPATH)
cmd/merlinserver/main.go:33:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/cli" in any of:
	/usr/lib/go-1.10/src/github.com/Ne0nd0g/merlin/pkg/cli (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/Ne0nd0g/merlin/pkg/cli (from $GOPATH)
cmd/merlinserver/main.go:32:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/core" in any of:
	/usr/lib/go-1.10/src/github.com/Ne0nd0g/merlin/pkg/core (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/Ne0nd0g/merlin/pkg/core (from $GOPATH)
cmd/merlinserver/main.go:31:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/logging" in any of:
	/usr/lib/go-1.10/src/github.com/Ne0nd0g/merlin/pkg/logging (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/Ne0nd0g/merlin/pkg/logging (from $GOPATH)
cmd/merlinserver/main.go:30:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/servers/http2" in any of:
	/usr/lib/go-1.10/src/github.com/Ne0nd0g/merlin/pkg/servers/http2 (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/Ne0nd0g/merlin/pkg/servers/http2 (from $GOPATH)
cmd/merlinserver/main.go:26:2: cannot find package "github.com/fatih/color" in any of:
	/usr/lib/go-1.10/src/github.com/fatih/color (from $GOROOT)
	/home/frank/merlin/src/github.com/Ne0nd0g/merlin/src/github.com/fatih/color (from $GOPATH)
Makefile:48: recipe for target 'server-windows' failed
make: *** [server-windows] Error 1
frank@ubuntu:~/merlin/src/github.com/Ne0nd0g/merlin$ echo $GOPATH
/home/frank/merlin/src/github.com/Ne0nd0g/merlin/

**Comment by Ne0nd0g** [comment]
It looks like your GOPATH changed, it should be `/home/frank/merlin`. Can you change your GOPATH and show its new value here?

**Comment by pentestitde** [comment]
Thats it! Thanks!

**Comment by Ne0nd0g** [comment]
Glad it got sorted out. If you want to chat about Merlin more, consider signing up for the BloodHound Slack and joining me in the #merlin channel. You can signup here: https://bloodhoundgang.herokuapp.com
