### ISSUE TITLE
Mimikatz Module is Outdated

### ISSUE THREAD

**Issue by benichmt1** [Ne0nd0g/merlin#47]
Windows 10 updates have broken the Get-ProcAddress function that is relied on by the Powershell Mafia module.

They are not updating the version of Invoke-Mimikatz in use by Merlin (see https://github.com/PowerShellMafia/PowerSploit/issues/293).

I know I can import the working module manually but my suggestion is if it's going to be tracked from an external source anyways, might as well track a repo that gets updated frequently (eg, Empire https://raw.githubusercontent.com/EmpireProject/Empire/master/data/module_source/credentials/Invoke-Mimikatz.ps1).

**Comment by Ne0nd0g** [comment]
That is a good idea @benichmt1 . I'll update the module.

**Comment by benichmt1** [comment]
Just so there's no confusion I forgot to mention that the most recent working version should be in the dev branch, not master, and there is a pending PR to fix it (https://github.com/EmpireProject/Empire/issues/1293)

**Comment by caseykey** [comment]
@Ne0nd0g is this issue being actively developed?

**Comment by Ne0nd0g** [comment]
I'll update the module to point to an updated version of Invoke-Mimikatz.ps1. As a workaround you can manually update the module JSON file at https://github.com/Ne0nd0g/merlin/blob/master/data/modules/windows/x64/powershell/powersploit/Invoke-Mimikatz.json#L26 by adding in https://raw.githubusercontent.com/BC-SECURITY/Empire/master/data/module_source/credentials/Invoke-Mimikatz.ps1

**Comment by Ne0nd0g** [comment]
Pushed code changes to dev. You can grab an updated copy from https://ci.appveyor.com/project/Ne0nd0g/merlin-i9c58/builds/31069490/artifacts until there is a new release of Merlin pushed out.
