### ISSUE TITLE
Agent nil objects/unchecked errors

### ISSUE THREAD

**Issue by C-Sto** [Ne0nd0g/merlin#52]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: Dev branch
* Merlin Build: /shrug
* Go Version: 1.11
* GOPATH Environment Variable: xx
* GOROOT Environment Variable: xx
* Operating System: windows

### Expected Behavior
Agent doesn't crash
### Actual Behavior
Agent crashes
### Steps to Reproduce Behavior
Interrupt the response to the agent
### Misc Information
Several locations either don't check error returns, or do, but then use a nil object, which leads to a panic due to a nil pointer dereference. offending lines I've found below:

https://github.com/Ne0nd0g/merlin/blob/ca24c53723ed85740dd6b25dfa4e54bd188f9fcc/pkg/agent/agent.go#L541-L542
https://github.com/Ne0nd0g/merlin/blob/ca24c53723ed85740dd6b25dfa4e54bd188f9fcc/pkg/agent/agent.go#L504-L511
https://github.com/Ne0nd0g/merlin/blob/ca24c53723ed85740dd6b25dfa4e54bd188f9fcc/pkg/agent/agent.go#L702-L711

As a side note, there appears to be unchecked errors during some json decoding too. May be worth going over line-by-line and ensuring no errors are silently passed over.

**Comment by Ne0nd0g** [comment]
Code base should be fixed to check all errors. I don't understand the issue with using a nil object to see if the error is nil. This seems like the correct way to do error checking https://blog.golang.org/error-handling-and-go

**Comment by C-Sto** [comment]
Sorry, I should have been more clearerer - I meant that errors were not interrupting program flow and it resulted in variables being assigned nil values (eg, in the second example resp2 is nil), and causes a nil pointer dereference (example 2 when the status code is checked).
