### ISSUE TITLE
Feature Request: Explicit System Command

### ISSUE THREAD

**Issue by Ne0nd0g** [Ne0nd0g/merlin#53]
Add a `system` command to Merlin server to explicitly execute commands on the host operating system. Merlin's current default is to execute any non-Merlin command on the host OS. However, some commands are both a valid Merlin command and host OS command such as `ls`.

**Comment by audibleblink** [comment]
How do feel about the pattern that some file transfer client and programs like vim use to handle this; preceding the local command with a `!`?

ie: `!ls` or `!taskkill`

**Comment by Ne0nd0g** [comment]
Yes, I'm good with that. I would rather use a format that is common to other tools.
