### ISSUE TITLE
Feature Request: Docker Container

### ISSUE THREAD

**Issue by softdream1981** [Ne0nd0g/merlin#63]
Can we have a docker merlin please.

**Comment by Ne0nd0g** [comment]
@softdream1981 I'll add this as a feature request and tag it with Help Wanted to see if someone is willing to put the time in to add in support for a Docker container.

**Comment by khast3x** [comment]
Also requesting this, thanks!

**Comment by Ne0nd0g** [comment]
Added Merlin to Docker Hub at the request of @khast3x . https://hub.docker.com/r/ne0nd0g/merlin or `docker pull ne0nd0g/merlin` . This will depend on me merging dev into master before it will work.

**Comment by softdream1981** [comment]
No docker yet?

**Comment by Ne0nd0g** [comment]
Pull request #64 was merged into dev but hasn't been pushed to master yet.

**Comment by Ne0nd0g** [comment]
Docker container support is implemented and merged into master.
