### ISSUE TITLE
Difference in case in "show options" / "set <option>"

### ISSUE THREAD

**Issue by Pernat1y** [Ne0nd0g/merlin#65]
### Prerequisite
* [+] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [+] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [+] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 0.6.0
* Merlin Build: -
* Go Version: go version go1.10.8 linux/amd64
* GOPATH Environment Variable: -
* GOROOT Environment Variable: -
* Operating System: Fedora 28

### Expected Behavior
Case of option name should match the one we are using to set it.

### Actual Behavior
Option names in "show options" output starting from uppercase, but option itself is in lowercase. This is confusing.

### Steps to Reproduce Behavior
![merlin](https://user-images.githubusercontent.com/29379145/53420650-d6c3e580-39e4-11e9-92cf-07bd19629da0.png)

**Comment by Ne0nd0g** [comment]
@pernat1y I think this was fixed in version 0.6.6. Can you download the latest version and see if the issue still exists?

**Comment by Ne0nd0g** [comment]
See Pull Request #44 https://github.com/Ne0nd0g/merlin/pull/44

**Comment by Pernat1y** [comment]
I have troubles building from dev branch. Will wait for release :)

**Comment by Ne0nd0g** [comment]
What problems were you having building from the Dev branch?
