### ISSUE TITLE
ERROR IN COMPILE THE MAIN>GO

### ISSUE THREAD

**Issue by Hackingzone** [Ne0nd0g/merlin#66]
main.go:31:2: cannot find package "github.com/Ne0nd0g/merlin/pkg" in any of:
        C:\Go\src\github.com\Ne0nd0g\merlin\pkg (from $GOROOT)
          C:\Users\cyber_windows\go\src\github.com\Ne0nd0g\merlin\pkg (from $GOPATH)
main.go:32:2: cannot find package "github.com/Ne0nd0g/merlin/pkg/agent" in any of:
        C:\Go\src\github.com\Ne0nd0g\merlin\pkg\agent (from $GOROOT)
        C:\Users\cyber_windows\go\src\github.com\Ne0nd0g\merlin\pkg\agent (from $GOPATH)
main.go:28:2: cannot find package "github.com/fatih/color" in any of:
        C:\Go\src\github.com\fatih\color (from $GOROOT)
        C:\Users\cyber_windows\go\src\github.com\fatih\color (from $GOPATH)

same error for linux and env path is set

**Comment by Ne0nd0g** [comment]
@hackingzone can you please fill out the issue template?

**Comment by Hackingzone** [comment]
@Ne0nd0g actually sorry i didn't get what are you trying to say please make the expainations which you sad above i am sorry for not understanding

**Comment by Ne0nd0g** [comment]
Create a comment with this information https://github.com/Ne0nd0g/merlin/blob/master/docs/ISSUE_TEMPLATE.md

**Comment by Ne0nd0g** [comment]
@Hackingzone I wanted to follow up with you one more time before I close this issue.

**Comment by V3ded** [comment]
@Hackingzone try running:
`go get github.com/Ne0nd0g/merlin/pkg` and `go get github.com/fatih/color` in your terminal/command prompt. 
This has worked for me some time ago. Hope it still does.

**Comment by Hackingzone** [comment]
It done i make a way for that issue thanks .

But ine thing i want to say that big slaute to you for this awesome tool
