### ISSUE TITLE
Feature Request: Module Support

### ISSUE THREAD

**Issue by ahhh** [Ne0nd0g/merlin#8]
I have a lot of golang code for agent features. I think these would best be implemented as modules. I was hoping you could make an example module so I could use it as a template for implementing more specialized agent features.

**Comment by Ne0nd0g** [comment]
Yes, I can do that. Give me a couple of weeks to get it sorted. I'm about 40% there all ready.

**Comment by Ne0nd0g** [comment]
I've got a new "modules" branch going but it is a hot mess. I would consider it an unstable alpha release that is subject to drastic changes while I make mind up on things.
