### ISSUE TITLE
cannot find package h2quic

### ISSUE THREAD

**Issue by ralphyz** [Ne0nd0g/merlin#80]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page

### Expected Behavior
I'm trying to build the docker image from the git repo commit 2c1146f on Aug 20 

### Actual Behavior
I get an error about missing package quic-go/h2quic.  I went to that github repo and it appears it has been renamed to http3.

### Steps to Reproduce Behavior
```
sudo docker build -t merlin .
Password:
Sending build context to Docker daemon  34.51MB
Step 1/8 : FROM golang:stretch
 ---> 710c1c6c29c8
Step 2/8 : MAINTAINER @audibleblink
 ---> Using cache
 ---> d50866a17f1f
Step 3/8 : RUN apt-get update && apt-get install -y git make
 ---> Using cache
 ---> 34fef87fbca6
Step 4/8 : RUN go get github.com/Ne0nd0g/merlin/...
 ---> Running in 35c1eed65de2
package github.com/Ne0nd0g/merlin/cmd/merlinagent
	imports github.com/lucas-clemente/quic-go/h2quic: cannot find package "github.com/lucas-clemente/quic-go/h2quic" in any of:
	/usr/local/go/src/github.com/lucas-clemente/quic-go/h2quic (from $GOROOT)
	/go/src/github.com/lucas-clemente/quic-go/h2quic (from $GOPATH)
The command '/bin/sh -c go get github.com/Ne0nd0g/merlin/...' returned a non-zero code: 1
```

### Misc Information
I'm on Mac Darwin 18.7.0

**Comment by Ne0nd0g** [comment]
What version of Go are you using?

**Comment by ralphyz** [comment]
I am using whatever is included in the Dockerfile.  I ran `git clone https://github.com/Ne0nd0g/merlin.git && cd merlin` as my first command, before the `sudo docker build...` command.

Looking in the Dockerfile `FROM golang:stretch` is the only reference I see.

**Comment by ralphyz** [comment]
It seems that h2quic was last in the guic-go repo on April 8, 2019 at this commit:
https://github.com/lucas-clemente/quic-go/tree/a63ee3d88f2103e85b76da80d08a29a76739e3c9

In the next commit on April 10, 2019, it was replaced with http3.

**Comment by Ne0nd0g** [comment]
Because I'm using Go modules now, this shouldn't be an issue. We just need to see if that docker image uses at least Go version 1.11 and modules are enabled.

**Comment by ralphyz** [comment]
Got it!  I will check that out.

**Comment by Ne0nd0g** [comment]
I would add the following commands to see what version of Go it is using and to enable module support

```
run go version
run export GO111MODULE=on
```
