### ISSUE TITLE
Dockerfile build fail

### ISSUE THREAD

**Issue by khast3x** [Ne0nd0g/merlin#81]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: master branch
* Operating System: Ubuntu

### Expected Behavior

Dockerfile successfully builds merlin

### Actual Behavior

Dockerfile build breaks at step 4

### Steps to Reproduce Behavior

```bash
root@dockerhost:~/merlin# docker build -t merlin .
Sending build context to Docker daemon   34.5MB
Step 1/8 : FROM golang:stretch
 ---> d30a8b8b92e2
Step 2/8 : MAINTAINER @audibleblink
 ---> Using cache
 ---> cd2eb209a713
Step 3/8 : RUN apt-get update && apt-get install -y git make
 ---> Using cache
 ---> 2a5f4fc64bfc
Step 4/8 : RUN go get github.com/Ne0nd0g/merlin/...
 ---> Running in e53a30612f04
package github.com/Ne0nd0g/merlin/cmd/merlinagent
	imports github.com/lucas-clemente/quic-go/h2quic: cannot find package "github.com/lucas-clemente/quic-go/h2quic" in any of:
	/usr/local/go/src/github.com/lucas-clemente/quic-go/h2quic (from $GOROOT)
	/go/src/github.com/lucas-clemente/quic-go/h2quic (from $GOPATH)
The command '/bin/sh -c go get github.com/Ne0nd0g/merlin/...' returned a non-zero code: 1
```

Cheers! :wave:

**Comment by Ne0nd0g** [comment]
I was able to build the Docker container without error. I'm wondering if the switch to Go 1.13 caused this error because the Vendor folder was removed. Could you try again or identify the version of go that is in use when the error is given?

**Comment by Ne0nd0g** [comment]
I stand corrected. I was using an old container myself. I was able to duplicate the error. I'm troubleshooting now.

**Comment by Ne0nd0g** [comment]
For some reason `go get` doesn't use the `go.mod` file. The quickest _workaround_ is to append `;exit 0` to the end of line 16 in the Dockerfile so that it reads like:
`RUN go get github.com/Ne0nd0g/merlin/...;exit 0`

**Comment by Ne0nd0g** [comment]
The better solution is to use `go install` install of `go get`.

**Comment by Ne0nd0g** [comment]
Looks like using `git clone` is a better choice over `go get`.

**Comment by Ne0nd0g** [comment]
Fixed in https://github.com/Ne0nd0g/merlin/commit/beaed0c3f8ba46ada579e9ac747efb65223d664f
