### ISSUE TITLE
Agent does not call back to Merlin server on Windows 10 

### ISSUE THREAD

**Issue by revronja** [Ne0nd0g/merlin#83]
Agent does not call back to Merlin server on Windows 10 . Confirmed the two hosts have connectivity.

**Comment by Ne0nd0g** [comment]
@revronja  please fill out the issue template

**Comment by Ne0nd0g** [comment]
https://github.com/Ne0nd0g/merlin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
