### ISSUE TITLE
Merlin 0.8 Agent cannot connect to server

### ISSUE THREAD

**Issue by ajnik** [Ne0nd0g/merlin#85]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 0.8.0
* Merlin Build: GOOS=windows GOARCH=amd64 go build -ldflags "-X main.url=https://192.168.37.135:443" -o merlin.exe main.go
* Go Version: 1.13.5 linux/amd64 
* GOPATH Environment Variable: /root/go
* GOROOT Environment Variable:
* Operating System: Windows Client (tested on Windows 10 and Server 2008R2) and Linux Server

### Expected Behavior
Agent should connect to the server

### Actual Behavior
When the client tries to check-in this error shows up:

```
[!]there was an error sending the agent OPAQUE user registration initialization
message:
there was an error communicating with the server:
404 (see screenshot)
```
The server also reports an error:

`[DEBUG]there was an error getting the agent's wait time` (see also screenshot)

The connection is not successful

### Steps to Reproduce Behavior
Already described

### Misc Information
See screenshots below
![Server](https://user-images.githubusercontent.com/15869724/71547868-c0d8d580-29a5-11ea-913b-c28acde827b8.png)
![agent](https://user-images.githubusercontent.com/15869724/71547869-c1716c00-29a5-11ea-9365-a6609122075c.png)

**Comment by Ne0nd0g** [comment]
What OS was the server running on when the error was encountered (i.e. Ubuntu 18.04)?

**Comment by ajnik** [comment]
> What OS was the server running on when the error was encountered (i.e. Ubuntu 18.04)?

It's on Kali 2019.4

**Comment by Ne0nd0g** [comment]
Did you download the Merlin Server from the releases page and run it or did you start the server with `go run`?

**Comment by ajnik** [comment]
> Did you download the Merlin Server from the releases page and run it or did you start the server with `go run`?

I started the server with go run. I will check if the same occurs with the precompiled version

**Comment by Ne0nd0g** [comment]
I ran the server on a clean install of Kali 2019.4 and did not get any errors. The `[DEBUG]there was an error getting the agent's wait time:` message is fine when an agent is performing authentication. Can you send back the entire text, to include the command to start the server, and all of the output from the server? Can you run the server with the `-v -debug` flags on top of what you normally do?

**Comment by ajnik** [comment]
> I ran the server on a clean install of Kali 2019.4 using both `go run` and using the precompiled version and did not get any errors. The `[DEBUG]there was an error getting the agent's wait time:` message is fine when an agent is performing authentication. Can you send back the entire text, to include the command to start the server, and all of the output from the server? Can you run the server with the `-v -debug` flags on top of what you normally do?

So on the server I ran `go run cmd/merlinserver/main.go -i 0.0.0.0 -v -debug` 
On the client (this exact error was on Server 2008R2) I ran `merlin.exe -url https://192.168.37.135 -v`

See screenshots below:
![server2](https://user-images.githubusercontent.com/15869724/71548561-aa844700-29b0-11ea-9304-131c5148d63e.png)
![W2k8R2](https://user-images.githubusercontent.com/15869724/71548566-cbe53300-29b0-11ea-8900-7bb1e3b790e6.png)

**Comment by Ne0nd0g** [comment]
If you're using VMs, verify the time on both the server and agent are the same down to the seconds.

**Comment by Ne0nd0g** [comment]
JWT validation is failing because the token is issued in the future. Likely because the time on your Windows server is ahead of your Merlin server.

**Comment by ajnik** [comment]
> JWT validation is failing because the token is issued in the future. Likely because the time on your Windows server is ahead of your Merlin server.

Yes that was the issue. Problem solved. Thank you for your time :)

**Comment by Ne0nd0g** [comment]
No problem. Stop by the #Merlin channel in the BloodHoundGang Slack if you want to chat more. Self-sign up: https://bloodhoundgang.herokuapp.com
