### ISSUE TITLE
Can't debug Merlin server, doesn't wait for the agent to connect and exit

### ISSUE THREAD

**Issue by g3rzi** [Ne0nd0g/merlin#89]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 0.8.0.BETA
* Merlin Build: nonRelease
* Go Version: go version go1.13 windows/amd64
* GOPATH Environment Variable: C:\Users\user1\go
* GOROOT Environment Variable: Go 1.13 C:\Go
* Operating System: Windows 10 x64 version 1803

### Expected Behavior
Merlin server is waiting for an agent to connect

### Actual Behavior
Merlin server listens to 127.0.0.1:443 and exit

### Steps to Reproduce Behavior
Run:  
```go
go run cmd/merlinserver/main.go
```
### Misc Information
I am using Goland 11.0.3 as IDE on Windows 10 x64 1803, I am trying to debug the server and the agent but when I run the server it doesn't wait for the agent to connect.

**Comment by Ne0nd0g** [comment]
Can you show me the output from when you run the commands?

Are you running it with administrative privileges so that I can bind to a port?

Use the `-debug` flag to get output

**Comment by g3rzi** [comment]
Yes,

This is the full output:  
```console
C:\Users\user1\go\src\merlin-master>go run cmd/merlinserver/main.go -debug

                               &&&&&&&&
                             &&&&&&&&&&&&
                            &&&&&&&&&&&&&&&
                          &&&&&&&&&&& &&&&
                         &&&&&&&&&&&&&  &&&&
                        &&&&&&&&&&&& &  &&&&
                       &&&&&&&&&&&&&     &&&&
                      &&&&&&&&&&&&&&&     &&&
                     &&&&&&&&&&&&&&&&&     &&&
                    &&&&&&&&&&&&&&&&&&&     &&&
                   &&&&&&&&&&&&&&&&&&&&&
                  &&&&&&&&&&&&&&&&&&&&&&&
                  &&&&&&&&&&&&&&&&&&&&&&&
                 &&&&&&&&&&&&&&&&&&&&&&&&&
                &&&&&&&&&&&&&&&&&&&&&&&&&&&
               &&&&&&&&&&&&&&&&&&&&&&&&&&&&&
              &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
             &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
       &&&&  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&   &&&
    &&&&&&  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&  &&&&&&
  &&&&&&&   &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&   &&&&&&&
&&&&&&&&&  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&  &&&&&&&&&
&&&&&&&&&&  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&  &&&&&&&&&&
&&&&&&&&&&&   &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&   &&&&&&&&&&&
&&&&&&&&&&&&&     &&&&&&&&&&&&&&&&&&&&&&&     &&&&&&&&&&&&&
  &&&&&&&&&&&&&&&          MERLIN         &&&&&&&&&&&&&&&
    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
       &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
           &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
                   Version: 0.8.0.BETA
                   Build: nonRelease
Merlin» [-]No certificate found at C:\Users\user1\go\src\merlin-master\data\x509\server.crt
[-]Creating in-memory x.509 certificate used for this session only.
[i]Additional details: https://github.com/Ne0nd0g/merlin/wiki/TLS-Certificates

[!]Listener was started using "merlin" as the Pre-Shared Key (PSK) allowing anyone decrypt message traffic.
[-]Consider changing the PSK by using the -psk command line flag.
[-]Starting h2 listener on 127.0.0.1:443

C:\Users\user1\go\src\merlin-master>


```

When I run:  
```console
go run cmd/merlinserver/main.go -debug
```

I am received the same output, did you want me to download the release version and use the `debug` flag?  
Because I am currently trying to debug the source code.

I didn't run it with administrative privileges.
After I read your comment I run the GoLand with administrator privileges but after I run:  
```console
go run cmd/merlinserver/main.go -debug  
```
I still exist after a second.

**Comment by Ne0nd0g** [comment]
I’m fairly confident that this is occurring because the terminal in GoLand is not running with administrative permissions. Can you open a cmd.exe or powershell.exe terminal as administrator, execute the go command, and send a screenshot including the terminal window title text showing administrator? 

Also, try switching to the dev branch. I put a fix in for this so it reports an error instead.

**Comment by g3rzi** [comment]
I had the same issue when I run `cmd.exe` as administrator but when after I tried the `dev` branch I saw what was the problem:  
```
[!]There was an error starting the h2 server on 127.0.0.1:443 listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
According to [stackoverflow](https://stackoverflow.com/a/10461978/2153777) it might happen because the socket is held by some process.

I changed the port to 1337 and now it works.

Thanks for your quick response!
