### ISSUE TITLE
Feature Request: REST API and Agent Status

### ISSUE THREAD

**Issue by dlmyb** [Ne0nd0g/merlin#9]
it seems that agent ID is similar to UUID.If agent program restarts and reconnects server, the agent will send another ID to the server which is different than before, and the server will store two agent id from the same agent. this situation always happens on some Windows PCs. Consider using some time-invariant ID, like agent macaddr?

**Comment by Ne0nd0g** [comment]
My concern is that there will be a collision if there are multiple instances of the agent running on a single host. A good example would be multiple users on the same terminal server. I'm also a fan of "two is one and one is none" methodology when dropping agents on a box during a pen test. Alternatively, we can hard code an agent ID at compile time if you think that would be useful?
Does this information influence your concern?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlmyb** [comment]
emmm…actually, could server automatically label some agents offline which do not response server ping requests? I am more concerned about managing agent table on the server easily, cause I think Merlin could be used on IOT devices.

**Comment by Ne0nd0g** [comment]
The server can't ping the agents. The agents initiate contact. The `agent info` command show you the last time an agent checked in though. However, I could mark an agent as stale if it hasn't checked in within the specified sleep interval? Merlin can 100% be run on IoT devices. I've run one on an ARM device.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dlmyb** [comment]
sounds nice. It would be better if Merlin server could provide things like Restful interfaces to obtain agent data and send commands.

**Comment by Ne0nd0g** [comment]
a gRPC interface was added in https://github.com/Ne0nd0g/merlin/commit/e80c47a7e441e39615d54368b871d004b3b698d3 to create similar functionality. Closing this issue.
