### ISSUE TITLE
Too much time (26+ seconds) to get response from agent 

### ISSUE THREAD

**Issue by g3rzi** [Ne0nd0g/merlin#91]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 0.8.0.BETA (`dev` branch)
* Merlin Build: `dev`
* Go Version: go1.14.4 linux/amd64
* GOPATH Environment Variable: `/home/jiren/go`
* GOROOT Environment Variable: `/usr/local/go`
* Operating System: Linux Ubuntu 16.04.3 LTS

### Expected Behavior
Fast output on server (maximum 4 seconds)

### Actual Behavior
On local server with agent that runs on the same machine it takes more than 26 seconds for the server to get response from the agent.
I am not sure why, is it because of HTTP/2? I shouldn't take so much time.  
I don't know what is the problem exactly but there couple of options to check where it take most of the time:
1. Before it goes to the agent
2. Time to get to the agent - **less likely** 
3. Before it goest to the server
4. Time to get to the server - **less likely**

### Steps to Reproduce Behavior
1. Start terminal with root `sudo -s`
2. Download agent and server for Linux from the releases
3. Start the server: `root# ./merlinServer-Linux-x64 -p 1338`
4. Start the agent: `root# ./merlinAgent-Linux-x64 -url https://127.0.0.1:1338`
5. After the server will get this kind of message: 
```
[+]New authenticated agent checkin for 40295678-2713-40ef-b6c7-9b0da1d4e84c at 2020-06-13T10:26:06Z
```
Run: 
```
Merlin» agent interact 40295678-2713-40ef-b6c7-9b0da1d4e84c
Merlin[agent][40295678-2713-40ef-b6c7-9b0da1d4e84c]» 
Merlin[agent][40295678-2713-40ef-b6c7-9b0da1d4e84c]» 
Merlin[agent][40295678-2713-40ef-b6c7-9b0da1d4e84c]» ls /
[-]Created job pzSzPrhLIf for agent 40295678-2713-40ef-b6c7-9b0da1d4e84c at 2020-06-13T10:26:24Z
Merlin[agent][40295678-2713-40ef-b6c7-9b0da1d4e84c]»  
```
6. Wait for output, it will take something like 25-28 seconds
### Misc Information
The agent is connected with HTTP/2 (h2):
```
Merlin» agent list

+--------------------------------------+-------------+------+--------+-------------+--------+
|              AGENT GUID              |  PLATFORM   | USER |  HOST  |  TRANSPORT  | STATUS |
+--------------------------------------+-------------+------+--------+-------------+--------+
| 40295678-2713-40ef-b6c7-9b0da1d4e84c | linux/amd64 | root | ubuntu | HTTP/2 (h2) | Active |
+--------------------------------------+-------------+------+--------+-------------+--------+
```

#### Demo
![merlin_time](https://user-images.githubusercontent.com/11998736/84566150-b9509180-ad77-11ea-99ed-a4b6d013e59b.gif)

**Comment by Ne0nd0g** [comment]
The default sleep time is 30 seconds before the agent checks back in. You can change that with `set sleep 10s` so that it calls back every 10 seconds instead.

**Comment by Ne0nd0g** [comment]
You can also use the `-sleep` command line argument when start the agent.

**Comment by Ne0nd0g** [comment]
@g3rzi Were you able to change the sleep time?

**Comment by g3rzi** [comment]
Yes, it looks better but let me do one more test and I will update here tomorrow

**Comment by g3rzi** [comment]
It seems to work much better, thanks.

I will keep work with this setup, thanks
