### ISSUE TITLE
Merlin 32 bit agent disconnects from 64 bit server: "connected with expired JWT"

### ISSUE THREAD

**Issue by g3rzi** [Ne0nd0g/merlin#93]
### Prerequisite
* [x] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD) - it is the same as case #87 
* [x] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [x] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 0.8.0.BETA (`dev` branch)
* Merlin Build: `dev`
* Go Version: go1.14.4 linux/amd64
* GOPATH Environment Variable: `/home/jiren/go`
* GOROOT Environment Variable: `/usr/local/go`
* Operating System: Linux Ubuntu 16.04.3 LTS

### Expected Behavior
32 bit agent connect to 64 bit server without disconnections.

### Actual Behavior
When the 64 bit server interacts with 32 bit agent it throws lots of errors:  
```
Merlin[agent][5b4e726b-f310-40f4-9295-d874061b9afb]» [!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Invalid Activity: StatusCheckIn
[!]Invalid Activity: StatusCheckIn
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Agent 5b4e726b-f310-40f4-9295-d874061b9afb connected with expired JWT. Instructing agent to re-authenticate
[!]Invalid Activity: StatusCheckIn
[!]Invalid Activity: StatusCheckIn
[!]Invalid Activity: StatusCheckIn
[!]invalid message type
[!]invalid message type
```

### Steps to Reproduce Behavior
1. Run 64 bit server with `-i <host_ip>-p 1337`
2. Compile 32 bit agent: `set GOARCH=386 | go build cmd/merlinagent/main.go`
3. Run 32 bit agent: `./main32 -url https://<host_ip>:1337 -sleep 1s`
4. Once it connects to the server, interact with the agent: `agent interact <agent_id>`
5. Run `ls`, it should print the output, run it again and should see the errors.

**Comment by g3rzi** [comment]
In #87 you suggested to increase the `-sleep` time, it seems to solve it when I run:  
```
./main32 -url https://<host_ip>:1337 -sleep 11s
```

Any idea why the difference between the 64 to 32 bit?

**Comment by Ne0nd0g** [comment]
I'm looking into it, but I don't know off the top of my head. It seems like the 32-bit agent just runs slower and isn't as quick to send/receive/process messages and I think that might be getting it out of sync. Every checkin request is run in its own thread so I wonder if the requests are getting out of sync because they can't process fast enough. I'm still looking into this more.

**Comment by Ne0nd0g** [comment]
Fixed as of https://github.com/Ne0nd0g/merlin/commit/43cecfe46eb71b8c75e29e662d35b6ea80379660 . Likely due to a restructure in how the sleep cycle and job processing works. The 32-bit agent is generally slower than the 64-bit agent.
