### ISSUE TITLE
Feature Request: Execute commands on all agents

### ISSUE THREAD

**Issue by bkmy625** [Ne0nd0g/merlin#98]
1. Is it possible to execute commands on all agents? 
For example if there are 200 agents it would be hard to change something on all of them if it has to be executed one by one
2. Also, is it possible to compile the agent with a backup domain? For example if it cant connect to the first domain to connect to the second
3. Is it possible to compile the agent with a custom -sleep time , because in the precompiled agents it can be specified in the command line, but when you compile the custom agent it is built in 30 seconds

**Comment by Ne0nd0g** [comment]
You could use a module to execute commands against all agents such as this one: https://github.com/Ne0nd0g/merlin/blob/master/data/modules/windows/x64/powershell/exec/powershell.json . 

I can work on something for the backup domain and sleep times.

**Comment by bkmy625** [comment]
Is it currently possible to change the sleep time, max retry and other configs on all agents that are already connected to the server. for example execute a global change to sleep time that will be done to all agents

**Comment by Ne0nd0g** [comment]
This feature was enabled through the [queue](https://merlin-c2.readthedocs.io/en/latest/server/menu/main.html#queue) command in 1aafa40023ba77346537035416a85742178a67fc
